# Generated by Django 4.2.5 on 2025-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_remove_interviewquestion_zipped_audio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="a.whittaker@student.uq.edu.au", max_length=254
                    ),
                ),
                (
                    "consent_form_url",
                    models.URLField(
                        default="https://docs.google.com/document/d/1Mzy_Ldz5YkXv94MG_OThwF5v5nZzrpSrRrNhVTdIrOg",
                        max_length=2048,
                    ),
                ),
                ("survey_1_url", models.URLField(default=None, max_length=2048)),
                (
                    "survey_1_secret",
                    models.CharField(default="Chocolate", max_length=100),
                ),
                ("survey_2_url", models.URLField(default=None, max_length=2048)),
                (
                    "survey_2_secret",
                    models.CharField(default="Factory", max_length=100),
                ),
            ],
        ),
    ]
