# Generated by Django 4.2.5 on 2025-08-25 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sim_brain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reflectionType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sim_brain.expert",
                    ),
                ),
            ],
        ),
    ]
