# Generated by Django 4.2.5 on 2025-09-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sim_brain", "0003_expert_created_reflection_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain", models.CharField(max_length=100)),
                ("filename", models.CharField(max_length=255)),
                (
                    "reflectionType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("filepath", models.CharField(max_length=255)),
                ("totalQuestions", models.IntegerField(default=0)),
                ("processedQuestions", models.IntegerField(default=0)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
