# Generated by Django 4.2.5 on 2025-09-10 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sim_brain", "0004_bulkquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkquestion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
