# Generated by Django 4.2.5 on 2025-09-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sim_brain", "0005_bulkquestion_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "bulkQuestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sim_brain.bulkquestion",
                    ),
                ),
            ],
        ),
    ]
