from django import template

register = template.Library()

@register.filter
# Generated by ChatGPT4o
def contains(value, arg):
    """
    Returns True if 'arg' is a substring of 'value'.
    """
    return arg in value

@register.filter
# Generated by ChatGPT4o
def filter_by_participant_id(queryset, id):
    """
    Filter a queryset of objects by participant ID.
    """
    return queryset.filter(participant__id=id)

@register.filter
def get_reflection_count_by_participant_id(queryset, id):
    """
    Get the count of reflections for a specific participant ID.
    """
    return queryset.filter(participant__id=id).count()